### ISSUE TITLE
[找不到原神紀錄卡片]問題

### ISSUE THREAD

**Issue by thc282** [KT-Yeh/Genshin-Discord-Bot#13]
該使用者已經嘗試清除資料 + 重新提交Cookie
[找不到原神紀錄卡片]問題
![image](https://user-images.githubusercontent.com/86453142/185115726-13a286fa-1ce1-4830-b4c5-fe83d0693167.png)

但其他功能仍能正常使用
![image](https://user-images.githubusercontent.com/86453142/185116193-2aff62e9-51f8-4c1c-900e-7660e741cd77.png)
![image](https://user-images.githubusercontent.com/86453142/185116264-5e87bded-2cc2-4475-aa1f-3642d2851c4b.png)

**Comment by KT-Yeh** [comment]
只讀到你美服的卡片，跟當前設定的UID不一樣

去網頁或app的個人中心看能不能讓它顯示亞服的資料

![](https://i.imgur.com/DsMp0dp.png)

**Comment by thc282** [comment]
謝謝你的幫忙, 理論上應該是可以的
> 目前的問題是, hoyolab那邊改了之后無法儲存更改后的資料(頁面重刷后變回更改前狀態)
 >或許是有其他方法

---
我建議可以在使用手冊(README.md)增加解決這個問題的辦法
可以讓其他遇到一樣情況的人當作一個參考
1.
![image](https://user-images.githubusercontent.com/86453142/185152064-0130bd13-c947-407a-8f32-55124636df40.png)

2.
![image](https://user-images.githubusercontent.com/86453142/185152702-43a7399d-adfb-4412-9709-ea063f78911e.png)

3.
![image](https://user-images.githubusercontent.com/86453142/185152823-08f1771b-e9b5-42a3-92dc-77e1800a3728.png)

**Comment by KT-Yeh** [comment]
好的~謝謝回報

> 目前的問題是, hoyolab那邊改了之后無法儲存更改后的資料(頁面重刷后變回更改前狀態)

所以改完亞服後，重整 hoyolab 就會回到美服嗎，那直接關掉網頁就還是停留在亞服狀態?

**Comment by thc282** [comment]
> 所以改完亞服後，重整 hoyolab 就會回到美服嗎，那直接關掉網頁就還是停留在亞服狀態?
是的, 重整后會變回初始狀態
改完后關掉所有有關網頁也是一樣, 大概率是米家那邊的問題呢~
