### ISSUE TITLE
沒有/showcase的選項

### ISSUE THREAD

**Issue by wibe01204** [KT-Yeh/Genshin-Discord-Bot#14]
如標題
自架機器人使用時有出現其他指令的提示，也可正常運作，唯獨沒有出現showcase的選項
從開數次也一樣，麻煩作者回復，謝謝~
![image](https://user-images.githubusercontent.com/90883053/191986100-15d0ee20-9afc-4514-9e45-e4662cd7d190.png)
![image](https://user-images.githubusercontent.com/90883053/191986139-e68b3828-fe14-4a1a-b8a3-0a6aff77bf1a.png)

**Comment by KT-Yeh** [comment]
你好，簡單來說有人把code整個拿去，假裝自己是原開發者並收取贊助，因此我github上拿掉/showcase功能，其他部分保持開源。

**Comment by wibe01204** [comment]
@KT-Yeh 哦~原來如此
那就沒事了~感謝! 辛苦了!!
