### ISSUE TITLE
关于原神国服cookie

### ISSUE THREAD

**Issue by HYBBWuXiDiXi** [KT-Yeh/Genshin-Discord-Bot#19]
看起来cookie只支持hoyoverse的，能否使用国服米游社的cookie

**Comment by KT-Yeh** [comment]
genshin.py可以支持國服，只是我沒有國服帳號，所以無法測試

**Comment by HYBBWuXiDiXi** [comment]
> 

我看了genshin.py的确可以支持国服cookie，但是我不太懂编写discord bot代码，如果您有做支持国服cookie的打算，我可以提供国服账号来协助您

**Comment by KT-Yeh** [comment]
好啊感謝你，我的Discord ID: KT#7777

**Comment by GauravM512** [comment]
#21
