### ISSUE TITLE
Bot Goes offline 

### ISSUE THREAD

**Issue by GauravM512** [KT-Yeh/Genshin-Discord-Bot#2]
Bot Goes offline after a few mins
code : websocket closed with status code 1000

**Comment by Lucifer7535** [comment]
How did u fixed this ?

**Comment by GauravM512** [comment]
Where do you host ?

**Comment by Lucifer7535** [comment]
Heroku

**Comment by Lucifer7535** [comment]
When it's more than 8hrs and no one has send the command then it goes offline.

I have to then restart it.

**Comment by GauravM512** [comment]
- Bots are not what the platform is designed for. Heroku is designed to provide web servers (like Django, Flask, etc). This is why they give you a domain name and open a port on their local emulator.

- Heroku's environment is heavily containerized, making it significantly underpowered for a standard use case.

- Heroku's environment is volatile. In order to handle the insane amount of users trying to use it for their own applications, Heroku will dispose your environment every time your application dies unless you pay.

- Heroku has minimal system dependency control. If any of your Python requirements need C bindings (such as PyNaCl binding to libsodium, or lxml binding to libxml), they are unlikely to function properly, if at all, in a native environment. As such, you often need to resort to adding third-party buildpacks to facilitate otherwise normal CPython extension functionality. (This is the reason why voice doesn't work natively on heroku.)

- Heroku only offers a limited amount of time on their free programme for your applications. If you exceed this limit, which you probably will, they'll shut down your application until your free credit resets.

From discord.py server

**Comment by Lucifer7535** [comment]
Ohk thanks for info, will look for another alternative or else mobile hosting through termux.😂
