### ISSUE TITLE
更新後無法啟動[No matching distribution found for yuanshen]

### ISSUE THREAD

**Issue by wibe01204** [KT-Yeh/Genshin-Discord-Bot#25]
![image](https://user-images.githubusercontent.com/90883053/208813364-b8401750-b776-4227-bdb1-09027e5c1deb.png)

麻煩指教~

**Comment by KT-Yeh** [comment]
你看一下專案內有沒有資料夾叫yuanshen

**Comment by wibe01204** [comment]
> 你看一下專案內有沒有資料夾叫yuanshen

好 我犯蠢了 應該知道問題了
