### ISSUE TITLE
支援多帳號的可能性

### ISSUE THREAD

**Issue by meme755144** [KT-Yeh/Genshin-Discord-Bot#28]
想請問未來是否會有推出多帳號查詢或是簽到等等的可能性呢
因為這樣小號的每日任務就可以少做一點了
同時也可以查看大小號的體力情況！

**Comment by KT-Yeh** [comment]
你好，因為多帳號的人不多，應該是不會做這功能。現在大部份指令可以查詢其他使用者，我建議可以在 discord 開個分身帳號並設定 cookie，之後即可在主帳號透過指令查詢分身帳號的體力情況
