### ISSUE TITLE
English Help Error

### ISSUE THREAD

**Issue by Murat1Ahmet** [KT-Yeh/Genshin-Discord-Bot#34]
Hey, 
can you help me fix this error please, I'm trying to change search database as [character, weapon, item, etc...] to english but i'm getting error, when i change resultLanguage: in genshin_dp/api.py line 52 to resultLanguage: str = GenshinDBLangENG.value, I get this as showing in the Image bellow
![image](https://github.com/KT-Yeh/Genshin-Discord-Bot/assets/132382465/d830040c-df58-426f-8b3f-d90e7594f67e)

**Comment by KT-Yeh** [comment]
Change the Element class to english in models/enums.py

**Comment by Murat1Ahmet** [comment]
I tried to change them to these 2 ways and both ways i got same error but with different names, what should i change them for then,
CRYO = "Ice", HYDRO = "Water", PYRO = "Fire", ELECTRO = "Lightning", GEO = "Rock", DENDRO = "Grass", ANEMO = "Wind", VOID = "Void"
![image](https://github.com/KT-Yeh/Genshin-Discord-Bot/assets/132382465/669a6e9e-a77e-4ec2-8f5b-712455f1f113)
and
CRYO = "Cryo", HYDRO = "Hydro", PYRO = "Pyro", ELECTRO = "Electro", GEO = "Geo", DENDRO = "Dendro", ANEMO = "Anemo", VOID = "Void"
![image](https://github.com/KT-Yeh/Genshin-Discord-Bot/assets/132382465/df09cec2-5aee-4d43-ab87-385aedbae6ec)

**Comment by KT-Yeh** [comment]
Find the element here.

https://genshin-db-api.vercel.app/api/characters?query=names&matchCategories=true&verboseCategories=true

**Comment by Lefengisbee** [comment]
Essentially, you need your element name in your class be like this:
CRYO = "Cryo"
HYDRO = "Hydro"
PYRO = "Pyro"
ELECTRO = "Electro"
GEO = "Geo"
DENDRO = "Dendro"
ANEMO = "Anemo"
VOID = "None"
Void can only be None
Only the first word can be capitalized

**Comment by Murat1Ahmet** [comment]
> Essentially, you need your element name in your class be like this: CRYO = "Cryo" HYDRO = "Hydro" PYRO = "Pyro" ELECTRO = "Electro" GEO = "Geo" DENDRO = "Dendro" ANEMO = "Anemo" VOID = "None" Void can only be None Only the first word can be capitalized

Oh i didn't think of this thank you so so much lol<3
