### ISSUE TITLE
ActionCards Error

### ISSUE THREAD

**Issue by TommyNoble1** [KT-Yeh/Genshin-Discord-Bot#37]
How to fix this issue pls, I get this error and search databse doesn't work 

[05-25 14:39:32]【ERROR】1 validation error for ActionCards
                　　　　__root__
                　　　　  none is not an allowed value (type=type_error.none.not_allowed)

**Comment by Murat1Ahmet** [comment]
+1

**Comment by Murat1Ahmet** [comment]
[05-26 13:48:12]【錯誤】5 validation errors for Characters
                　　　　__root__ -> 31 -> images -> icon
                　　　　  field required (type=value_error.missing)
                　　　　__root__ -> 31 -> images -> sideicon
                　　　　  field required (type=value_error.missing)
                　　　　__root__ -> 31 -> images -> nameicon
                　　　　  field required (type=value_error.missing)
                　　　　__root__ -> 31 -> images -> nameiconcard
                　　　　  field required (type=value_error.missing)
                　　　　__root__ -> 31 -> images -> namesideicon
                　　　　  field required (type=value_error.missing)

**Comment by KT-Yeh** [comment]
It's a Genshin DB API bug. It should be fixed now.
