### ISSUE TITLE
Support timezones?

### ISSUE THREAD

**Issue by GauravM512** [KT-Yeh/Genshin-Discord-Bot#5]
The bot currently support timezone based on the host , can you add seperate timezone according to the Discord guild region.

**Comment by KT-Yeh** [comment]
Most of my user are in Taiwan, so I have no plan to do this.
Maybe you can try Discord message formatting to solve this by yourself.
Convert the time into Unix timestamp and send through message like `<t:1618953630>`, the user will see the exact time in their timezone.
Reference: https://discord.com/developers/docs/reference#message-formatting
