### ISSUE TITLE
redeem兌換用不到

### ISSUE THREAD

**Issue by 0oxiaokiaoo0** [KT-Yeh/Genshin-Discord-Bot#6]
使用兌換的時候會出錯誤然後後台會說
 ERROR [例外]<class 'discord.app_commands.errors.CommandInvokeError'>: Command 'redeem兌換' raised an exception: HTTPException: 400 Bad Request (error code: 50006): Cannot send an empty message
不管放什麼兌換碼都一樣

**Comment by GauravM512** [comment]
update genshin.py directly from github.
`pip install -U git+https://github.com/thesadru/genshin.py`

Make sure you uninstall previous genshin.py by 
`pip uninstall genshin`

**Comment by 0oxiaokiaoo0** [comment]
ok

**Comment by 0oxiaokiaoo0** [comment]
i update alr but still not working

**Comment by GauravM512** [comment]
Did you pip uninstall?

**Comment by 0oxiaokiaoo0** [comment]
yes

**Comment by GauravM512** [comment]
It should work then , restart the bot with new g.py
