### ISSUE TITLE
Implementing Redemption Code by Accepting account_id_v2 and cookie_token_v2 from users

### ISSUE THREAD

**Issue by Lucifer7535** [KT-Yeh/Genshin-Discord-Bot#63]
Can I proceed with creating a pull request for this implementation?

**Comment by KT-Yeh** [comment]
Is it still easy for the cookie to expire when using cookie_token to redeem a code now?

**Comment by Lucifer7535** [comment]
no, if you have setup account_id_v2 and cookie_token_v2 it does'nt give that error any more. Also i tried redeeming codes multiple  times but did'nt got the error.

also these 2 values needed to be taken from [hoyoverse official website](https://genshin.hoyoverse.com/en/gift), where we redeem the code.
