### ISSUE TITLE
Where did you get the data from for /data/game?

### ISSUE THREAD

**Issue by Lucifer7535** [KT-Yeh/Genshin-Discord-Bot#7]
For the following files :
1. artifacts.py
2. characters.py
3. fight_prop.py
4. weapons.py

**Comment by GauravM512** [comment]
For 1,2 and 3 use [This Repo](https://github.com/Dimbreath/GenshinData/tree/master/ExcelBinOutput) or just translate it

For 4 , you can get it from the official [API](https://github.com/EnkaNetwork/API-docs) documentation

**Comment by Lucifer7535** [comment]
Ok thanks 👍

**Comment by Lucifer7535** [comment]
> For 1,2 and 3 use [This Repo](https://github.com/Dimbreath/GenshinData/tree/master/ExcelBinOutput) or just translate it
> 
> For 4 , you can get it from the official [API](https://github.com/EnkaNetwork/API-docs) documentation

Do u know the name of file for artifacts.py. I was searching for it but was unable to found
